// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Reprocessing = require("/Users/gabriel/Documents/GitHub/pkuosa-gabriel/obdurate/node_modules/reprocessing/src/Reprocessing.js");
var Reprocessing_Env = require("/Users/gabriel/Documents/GitHub/pkuosa-gabriel/obdurate/node_modules/reprocessing/src/Reprocessing_Env.js");
var Reprocessing_Draw = require("/Users/gabriel/Documents/GitHub/pkuosa-gabriel/obdurate/node_modules/reprocessing/src/Reprocessing_Draw.js");
var Reprocessing_Constants = require("/Users/gabriel/Documents/GitHub/pkuosa-gabriel/obdurate/node_modules/reprocessing/src/Reprocessing_Constants.js");

console.log("Hello World!");

function setup(env) {
  return Reprocessing_Env.size(200, 200, env);
}

function draw(_state, env) {
  Reprocessing_Draw.background(Reprocessing_Constants.black, env);
  Reprocessing_Draw.fill(Reprocessing_Constants.red, env);
  return Reprocessing_Draw.rect(/* tuple */[
              50,
              50
            ], 100, 100, env);
}

Reprocessing.run(setup, undefined, draw, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);

exports.setup = setup;
exports.draw = draw;
/*  Not a pure module */
